version: '3.8'

services:

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    networks:
      - inception
    dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      -mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    build: requirements/nginx/.
    container_name: nginx
    networks:
      - inception
    dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: on-failure

  wordpress:
    build: requirements/wordpress/.
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
  networks:
      inception:
      driver: bridge